import type { Metadata } from "next";

import "./globals.css";

import Header from "@/components/Header";
import QueryProvider from "@/components/QueryProvider";

import ReduxProvider from "./store/Provider";

export const metadata: Metadata = {
  title: "Pokemon App",
  description: "Generated by Tushal Barvaliya.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body>
          <Header />
          <ReduxProvider>{children}</ReduxProvider>
        </body>
      </QueryProvider>
    </html>
  );
}
